services:
    server:
        image: itzg/minecraft-server:java17-alpine
        ports:
            - "25565:25565"
        volumes:
            - ./data:/data
        environment:
            EULA: "TRUE"
            TYPE: "NEOFORGE"
            VERSION: "1.20.1"
            PACKWIZ_URL: "https://raw.githubusercontent.com/mxxntype/spectral/main/pack.toml"

            MEMORY: "12G"
            USE_AIKAR_FLAGS: "true"
            ENABLE_AUTOPAUSE: "true"

            MODE: "survival"
            DIFFICULTY: "hard"
            MAX_PLAYERS: "8"
            ALLOW_FLIGHT: "true"

            MOTD: "Le server for cats :3"
            ICON: "https://raw.githubusercontent.com/mxxntype/spectral/main/assets/icon.png"

            ONLINE_MODE: "false"
            # ENABLE_WHITELIST: "true"
            # WHITELIST: |
            #     mxxntype
            # OPS: |
            #     mxxntype

            RCON_CMDS_STARTUP: |-
                /team add New
                /team add Old

            RCON_CMDS_ON_CONNECT: |-
                /team join New @a[team=]
                /clear @a[team=New]
                /team join Old @a[team=New]

            RCON_CMDS_FIRST_CONNECT: |-
                /whitelist on
                /whitelist add mxxntype
                /op mxxntype

