name = "Spectral"
author = "mxxntype"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2e208a9f2bc2cf040b16db47ce40829d271469624562d80e17dafbd0a5820f65"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
