name = "Spectral"
author = "mxxntype"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "38234c8df1051ccaf0edf523ead03ac205542162d6385dea5b43d6681499cb4c"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
