name = "Spectral"
author = "mxxntype"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "775efb39be51b0080b0f4e03dea4997a224639b0761421f8353ab5ed018bc397"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
