name = "Spectral"
author = "mxxntype"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b1e28899d7d96671903432218269a11a5c434308c4cea7e0fcceba7a7f2863be"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
